### ISSUE TITLE
pre- or post-activation?

### ISSUE THREAD

**Issue by caka4583** [hukkai/rescaling#2]
I stumbled accross the notation in the paper. There x_k is the output of the k-th block calculated by
        x_k = F_k(x_{k-1}) + x_{k-1}
The paper states that it focuses on post-activation ResNets; the code also is based on post-activation ResNets.
So I was wondering where does the ReLU happen in the above equation? And which Variances are compared in the paper? Before ReLU or after?

It would really help me to know what F_k consists of (in the case of Bottleneck Blocks).
My considerations are 
      1) F_k = conv \circ ReLU \circ conv \circ ReLU \circ conv
           and after that ReLU that is somehow missing in the first equation or 
     2) F_k =  conv \circ ReLU \circ conv \circ ReLU \circ conv \circ ReLU
          but then the analysis in the paper is for preactivation ResNets.

And if the first consideration is right - wich variances are compared when talking about Var(x_k)? Before or after ReLU?

I would be really grateful if you could clarify this for me.

**Comment by hukkai** [comment]
Thanks for reading our paper. You are right. The analysis is only good for pre-activation. If you want to be strict about the analysis, we admit that our analysis is not precise for post-activation.

However, it also works **roughly** for post-activation when the residual branch is scaled by a small number. Consider post-activation with x_k = ReLU(x_{k-1} + \alpha_k F_k). Since x_{k-1} comes from ReLU, it is non-negative. If \alpha_k is a small number, x_{k-1} + \alpha_k F_k is almost positive, and ReLU does not change the variance very much.  

Given this reason, the code can work on both post-activation and pre-activation. In fact, pre-activation's performance is even better as shown in [1]. For the reason why we choose to implement with post-activation, we are following an early work [2] who faced the similar problem, and want to be consistent with them for a fair comparison. Please let me know if you have any further questions.

[1] Batch Normalization Biases Residual Blocks Towards the Identity Function in Deep Networks.
[2] Fixup Initialization: Residual Learning Without Normalization.

**Comment by hukkai** [comment]
If any questions, feel free to re-open this issue. Thanks!
